### ISSUE TITLE
[ERP][Chức năng Thông báo thay đổi giá] Không niêm yết được cho sản phẩm ứng nhà cung cấp đã có giá mua/bán ở 2 server 9090 và 8080

### ISSUE THREAD

**Issue by phatls** [luantm/FEEDBACKs#1]
[Precondition]
- Sản phẩm ứng với nhà cung cấp đã có giá mua/bán ở 2 server 9090 và 8080
- Trong [Thông báo thay đổi giá] có sản phẩm trên

[Procedure]
1. Vào server 9090, Mua hàng -> Chính sách giá mua -> Thông báo đổi giá 
2. Kiểm tra sản phẩm BK0000002877 của NCC: NCC059
(BK0000002877 của NCC: NCC059 đã có giá mua và bán ở 2 server)
3. Chọn Niêm Yết Giá cho sản phẩm  BK0000002877 của NCC: NCC059
4. Vào server 8080, check giá bán BK0000002877 của NCC: NCC059

[Actual Result]
Giá bán không cập nhât

[Expected Result]
Giá bán từ server 9090 chuyển qua 8080.

Ghi chú: Đối với BKCODE của NCC không có giá bán ở 8080 thì Niêm Yết Giá nó chuyển được từ server 9090 chuyển qua 8080.

**Comment by phatls** [comment]
Ví dụ mẫu, bộ phận fix chỉ cần vào trả lời rồi assign lại cho Phát

**Comment by IMSSvc01** [comment]
[Cause]
Chức năng niêm yết giá không cập nhật thông tin vào trường giá bán hiển thị (đã fix)
[Impact]
None

**Comment by phatls** [comment]
Fixed
