### ISSUE TITLE
[ERP] Ko thể xoá giá bán và giá mua ở server 9090

### ISSUE THREAD

**Issue by phatls** [luantm/FEEDBACKs#12]
[Reprocedure]
1. Vào server 9090
2. Bán hàng -> Chính sách bàn hàng -> Ma trận giá bán 
3. Xoá 1 hoặc nhiều dòng

[Actual result] 
Ko xoá được

[Expected result]
Xoá được như trước khi cập nhật 9/5/2016

PS: 
- Giá mua: cũng ko xoá được

**Comment by IMSSvc01** [comment]
Xong
