### ISSUE TITLE
[Sản phẩm] Bản lề cối 

### ISSUE THREAD

**Issue by phatls** [luantm/FEEDBACKs#15]
Liên quan tất cả mã bản lề cối, em xử lý nhanh cho anh:
1. Search PIM sản phẩm: chỉ cho Vũng Tàu đặt (còn ở Tây Ninh, hệ thống ko xử lý, em tự chuyển thành BXR cho nhóm tự doanh Tây Ninh)
2. Search server Chiểu: chỉ cho Vũng Tàu đặt

**Comment by luantm** [comment]
1.Xóa mapping bản lề cối.
2.Chỉ VT mới search được trên SV Chiểu.
