### ISSUE TITLE
[Tiện ích] Điều chỉnh vị trí cột Mô Tả trong Bán hàng -> Báo Giá Bán Nội Địa

### ISSUE THREAD

**Issue by phatls** [luantm/FEEDBACKs#16]
[Vấn đề hiện tại]
Khách hàng/sale thêm ghi chú cho đơn hàng, nhưng trên ERP, cột Mô Tả nằm bị khuất màn hình nên bộ phận báo giá bỏ mất thông tin thường xuyên

[Mong đợi]
Bố trí lại vị trí cột Mô tả trong [Bán hàng -> Báo Giá Bán Nội Địa] cho phù hợp:
Đề xuất: Cột Mô Tả => Chuyển nằm ngay sau cột Mã KH Thanh Toán

Server: BKVINA + tất cả server con

**Comment by IMSSvc01** [comment]
xong
[Impact]
None

**Comment by phatls** [comment]
Chưa cập nhật Server: BKVINA + tất cả server con
