### ISSUE TITLE
[Công thức tính giá] Công thức tính giá đối với trường hợp muốn chiết khấu cho khách hàng

### ISSUE THREAD

**Issue by phatls** [luantm/FEEDBACKs#2]
# > Khách hàng phản ánh:

> Giá máy mài BKCODE 2980, lần trước 442400 đồng, sao lần này giá đến 463000 đồng.

Gặp vấn đề trên do hệ thống ghi nhận:
**1. Đối với công thức tính giá hiện tại: có 2 loại:**
Loại 1: Tỷ lệ 
Áp dụng công thức: Giá bán = Giá mua / (1 - Tỷ lệ/100) làm tròn 1 số tới hàng chục
Loại 2: Cụ thể
Áp dụng công thức: Giá bán = Giá mua + giá trị cụ thể

=> Công thức tỷ lệ trên không đúng với trường hợp: MUỐN CHIẾT KHẤU CHO KHÁCH HÀNG
Tức trường hợp này tỉ lệ là âm.

*_Ví dụ: *_Giá cái máy mài 560.000 đồng, BKVINA muốn chiết khấu cho khách hàng thêm 21%
=> Tỷ lệ = -21 (số âm có nghĩa là chiết khấu trên giá mua)
=> Giá bán = Giá mua \* (1+Tỷ lệ/100) = 560000*79/100 = 442400 đồng

(Nếu áp dụng công thức hiện tại: Giá bán = Giá mua / (1-Tỷ lệ/100)  = 463000 đồng.
=> Công thức này ko đúng cho trường hợp chiết khấu cho khách hàng, chỉ đúng cho trường hợp tỷ lệ dương)

**2. TỔNG KẾT LẠI, CÔNG THỨC TÍNH GIÁ CẦN ĐƯỢC NÂNG CẤP CÓ 3 LOẠI:**
Loại 1: Tỷ lệ dương (tức giá bán muốn cao hơn giá mua)
Áp dụng công thức: Giá bán = Giá mua / (1 - Tỷ lệ/100) làm tròn 1 số tới hàng chục

Loại 2: Tỷ lệ âm (tức chiết khấu từ giá mua cho khách hàng)
Áp dụng công thức: Giá bán = Giá mua \* (1 + Tỷ lệ/100) làm tròn 1 số tới hàng chục

Loại 3: Cụ thể
Áp dụng công thức: Giá bán = Giá mua + giá trị cụ thể

**Comment by mcau2010** [comment]
Cái này Việt xem có làm thêm 1 loại công thức nữa không nhé?
Có thêm vẫn tốt hơn.

**Comment by IMSSvc01** [comment]
Nên có tài liệu ngắn gọn về cách tính để V dễ thực hiện hơn. (ví dụ, chiết khấu từ giá mua là gì?)

**Comment by IMSSvc01** [comment]
Nếu mọi người xác nhận thì V tiến hành cài đặt vào hệ thống
- xác định: Giá mua ở các công thức trên là giá mua trước khi chiết khấu mua hàng hay sau khi chiết khấu mua hàng?
- Loại 2: Tỷ lệ âm (tức chiết khấu từ giá mua cho khách hàng)
  Áp dụng công thức: Giá bán = Giá mua \* (1 + Tỷ lệ/100) làm tròn 1 số tới hàng chục
  Ví dụ:
  Chiết khấu 5% từ giá mua thì công thức có phải như thế này không:
  Giá bán = Giá mua \* (1 - 5/100)

Với công thức này V hiểu: Giá mua là giá trước khi NCC chiết khấu và giá bán chắc chắn thấp hơn giá mua trước khi chiết khấu (vì nếu áp dụng cho giá mua sau khi chiết khấu thì giá bán còn thấp hơn nữa)

**Comment by phatls** [comment]
(https://github.com/luantm/FEEDBACKs/files/233932/LUANTM25042016_LOI.DUYET.DONG.GOI.xlsx)

**Comment by IMSSvc01** [comment]
Đã thêm công thức tính giá

**Comment by phatls** [comment]
Fixed
