### ISSUE TITLE
[DAILY][ERP]Lỗi không thể duyệt đóng gói cho DHBN160400663 với BK0000001370, BK0000001371, BK0000001372

### ISSUE THREAD

**Issue by luantm** [luantm/FEEDBACKs#4]
[LUANTM25042016_LOI DUYET DONG GOI.xlsx](https://github.com/luantm/FEEDBACKs/files/234012/LUANTM25042016_LOI.DUYET.DONG.GOI.xlsx)

**Comment by phatls** [comment]
**[Precondition]**<br>
None<br>

**[Procedure]**<br>
Thực hiện việc ghi sổ cho  đơn hàng bán DHBN160400663 = API:<br>
http://beka.vn:90/api/BkBin/TransferBinWithTrace<br>
Post nội dung: <br>
[BK0000001370.txt](https://github.com/luantm/FEEDBACKs/files/234065/BK0000001370.txt)

**[Actual Result]**<br>
409:BK0000001370:2 CUON25-.<br>

**[Expect result]**<br>
Không bị lỗi trên<br>

**Ghi chú:**<br>
1. Bị lỗi tương tự với <br>
   BK0000001371 và BK0000001372<br>
   Với lần lượt nội dung post:<br>
   [BK0000001371.txt](https://github.com/luantm/FEEDBACKs/files/234066/BK0000001371.txt)
   [BK0000001372.txt](https://github.com/luantm/FEEDBACKs/files/234067/BK0000001372.txt)<br>
2. ERP giúp tìm cách thông báo lỗi nhanh hơn cho lần sau đối với trường hợp gặp tương tự lỗi này, nhưng với BKCODE khác, BIN khác.<br>
3. API hỗ trợ cho xem danh sách đơn hàng bán cần xuất kho:
   http://beka.vn:90/api/BkBin/GetItemListInBinByOrderNo/DHBN160400663/INV01001

**Comment by IMSSvc01** [comment]
[Cause]
Lỗi xảy ra trong quá trình phân bổ mua hàng. Ví dụ: khách hàng đặt mua 3, Bách Việt đăng kí mua 3, sau đó kiểm kho thấy có 1 nên xuất 1 trước. ==> sau khi nhập kho mua hàng 3 và xuất đóng gói 3 là sai (vì thực tế đã xuất 1, giờ chỉ cần xuất 2). Giải pháp: chuyển bớt 1 qua PRS.
[Impact]
Buộc phải tăng 1 ở rổ 0 cho đủ số lượng lưu kho (mua 3, xuất 2, dư 1 lưu kho)

**Comment by luantm** [comment]
![image](https://cloud.githubusercontent.com/assets/18589252/14778751/f3013eb8-0afe-11e6-9293-66167c54f37a.png)

**Comment by IMSSvc01** [comment]
Đã cải tiến
[Impact]
- Crossdocking đơn hàng mua có sản phẩm bị loại bỏ sẽ được yêu cầu nhập rỗ 0
