### ISSUE TITLE
[ERP][Công thức tính giá] Giá trị thập phân công thức tính giá không có ý nghĩa

### ISSUE THREAD

**Issue by phatls** [luantm/FEEDBACKs#5]
[Precondition]
None

[Reproduce]
1. Vào Mua hàng -> Chính sách giá mua -> Công thức tính giá  
2. Điểu chỉnh cột [Giá trị] bằng 1 giá trị mới có thập phân: ví dụ: 6.89
3. Click ở 1 dòng khác cho Lưu lại
4. Chọn Home -> Reload lại

[Actual result]
Công thức tính giá tự chuyển về: 7.00

[Expect result]
Vẫn giữ 6.89

**Comment by IMSSvc01** [comment]
[Cause]
Do thiết kế database không chừa phần thập phân
[Impact]
None

**Comment by phatls** [comment]
Fixed
