### ISSUE TITLE
[daily][ERP] Sai đơn giá tại đơn hàng bán Bách Việt

### ISSUE THREAD

**Issue by luantm** [luantm/FEEDBACKs#6]
![image](https://cloud.githubusercontent.com/assets/18589252/14810531/95943b94-0bbd-11e6-9c66-9fa2ae831e6d.png)

**Comment by luantm** [comment]
Hi anh Việt,
1.Trường hợp 1: toa hàng gởi lên từ điện toạn->cập nhật tt->đơn giá đúng ma trận giá bán
2.Trường hợp 2:báo giá đã cập nhật tt(có mã hàng)->điều chỉnh đơn giá = 0->đơn giá mới = ma trận giá bán \* hệ số quy đổi của đơn bị bán tương ứng.
A check lại issue này nha.

**Comment by IMSSvc01** [comment]
Xong
