### ISSUE TITLE
[ERP][BKVINA] Đơn vị cơ bản cho mã TA mới

### ISSUE THREAD

**Issue by luantm** [luantm/FEEDBACKs#7]
![image](https://cloud.githubusercontent.com/assets/18589252/14845251/278867fe-0c87-11e6-9bc9-bb7db65464c8.png)

**Comment by IMSSvc01** [comment]
[Cause]
Không cập nhật đơn vị cơ bản khi tạo mã tạm
[Impact]
None

**Comment by luantm** [comment]
[Actual result]
Mã tạm mới tạo ra vẫn chưa có đơn vị cơ bản

**Comment by IMSSvc01** [comment]
[Cause]
Nhầm công ty
