### ISSUE TITLE
[ERP][Nhập hoá đơn mua] Đối với trường hợp giá mua mới bị tăng đột biến so với lần trước

### ISSUE THREAD

**Issue by phatls** [luantm/FEEDBACKs#8]
Đây ko phải là bug mà là tính năng tăng ràng buộc KHÂU KẾ TOÁN KHO:

Chức năng Nhập hoá đơn mua [Mua hàng -> Đơn hàng mua nội địa]:
Nếu giá mua thay đổi vượt mức cho phép, tức: [Giá mua mới] lớn hơn [Giá mua cũ] 5%
Thì cảnh báo giá mua vượt giá bán.

Chi tiết có thể liên hệ với Phát.

**Comment by IMSSvc01** [comment]
Đã thực hiện chức năng (test ở port: 9091)
